### ISSUE TITLE
Return in inner function inside effect swears

### ISSUE THREAD

**Issue by evgeniyworkbel** [ConstiLine/eslint-plugin-react-useeffect#1]
**Steps to reproduce:**
1. Define useEffect in react component
2. Declare some function inside effect and return smth from it (or return without value)
3. Call this function

**Code example:**
```
    useEffect(() => {
        const createSmth = () => {
            const random = Math.random();
            return random;
        };
        createSmth();
    }, []);
```

**Expected behaviour:**
Rule does not affect by this return

**Actual behaviour:**
Rule affects by this return

**Comment by ConstiLine** [comment]
Thanks for posting. This bug does exist and will be fixed in an upcoming patch

**Comment by ConstiLine** [comment]
@evgeniyworkbel Patch 1.0.10 is out, this should solve the problem

**Comment by evgeniyworkbel** [comment]
@ConstiLine, I have upgrated plugin to 1.0.11, but the bug is still exist

**Comment by ConstiLine** [comment]
@evgeniyworkbel Please check with the new patch, it has added checking of other types of functions as well. Apparently, your error is somehow related to it

**Comment by evgeniyworkbel** [comment]
@evgeniyworkbel yes, now it works, thx!
